### ISSUE TITLE
protoc语法允许在message中内嵌enum

### ISSUE THREAD

**Issue by zy475459736** [venus-boot/saluki#1]
saluki/saluki-plugin/saluki-plugin-common/src/main/java/com/quancheng/plugin/common/CommonProto2Java.java
这里的doprint方法是否可以改成：

    private void doPrint(FileDescriptorProto fdp, String javaPackage, String outerClassName) {
        ArrayList<DescriptorProto> messageDescList = new ArrayList(fdp.getMessageTypeList());
        ArrayList<ServiceDescriptorProto> serviceDescList = new ArrayList(fdp.getServiceList());
        ArrayList<EnumDescriptorProto> enumDescList = new ArrayList(fdp.getEnumTypeList());

        messageDescList.stream().filter(temp->temp.getEnumTypeList()!=null)
                .forEach(temp->enumDescList.addAll(temp.getEnumTypeList()));

        printEnum(enumDescList, javaPackage, outerClassName);
        printMessage(messageDescList, javaPackage, outerClassName);
        printService(serviceDescList, javaPackage);
    }

**Comment by geercode** [comment]
啊呦 校友

**Comment by zy475459736** [comment]
那肯定是学长了。学长好。

**Comment by linking12** [comment]
@zy475459736 多谢，已经合入到master上了

**Comment by linking12** [comment]
@zy475459736 多谢，已经合入到master上了
